### ISSUE TITLE
libfontmanager.so: libfreetype.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by yincangshiwei** [Tencent/TencentKona-8#74]
docker image ccr.ccs.tencentyun.com/konajdk_repo/tencentkona_8:latest
error：
/opt/TencentKona-8.0.4-272/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

**Comment by linzang** [comment]
Hi @yincangshiwei，

Thanks for your info. please try following steps:
`apt-get install libfreetype6`
Or:
`yum install libfreetype6`

BRs,
Lin

**Comment by yincangshiwei** [comment]
in the docker environment：
'apt-get' and 'yum'  command not find

**Comment by linzang** [comment]
Thanks for your suggestion! we will handle it and let you know. Thanks!

**Comment by ldaxr** [comment]
@yincangshiwei .

**Comment by ldaxr** [comment]
@yincangshiwei . Hi , please try this command "apk add freetype", and libfreetype.so.6 wil be found at /usr/lib/libfreetype.so.6
TencentKona's docker image is based on alpine, and use 'apk' as package manager.
Thanks for found this problem and support for Kona.

**Comment by yincangshiwei** [comment]
> 
@linzang 
konajdk/konajdk:8 This problem also exists

**Comment by yincangshiwei** [comment]
> 
@ldaxr 
Thank you for your answer，‘apk add freetype’ Can be used，but cannot be solved。java code error 'sun.awt.FontConfiguration.getVersion' java.lang.NullPointerException.

**Comment by ldaxr** [comment]
@yincangshiwei , Could you give us a testcase to reproduce this problem? We will try to solve it.

**Comment by yincangshiwei** [comment]
> 

@ldaxr 'hutool-captcha' tool。err function 'cn.hutool.captcha.AbstractCaptcha.createCode'。

java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:441)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:386)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.awt.Font.getFont2D(Font.java:491)
        at java.awt.Font.access$000(Font.java:224)
        at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
        at sun.font.FontUtilities.getFont2D(FontUtilities.java:200)
        at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:669)
        at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:835)
        at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:50)
        at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
        at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2933)
        at cn.hutool.core.img.GraphicsUtil.drawString(GraphicsUtil.java:120)
        at cn.hutool.core.img.GraphicsUtil.drawStringColourful(GraphicsUtil.java:84)
        at cn.hutool.captcha.CircleCaptcha.drawString(CircleCaptcha.java:83)
        at cn.hutool.captcha.CircleCaptcha.createImage(CircleCaptcha.java:66)
        at cn.hutool.captcha.AbstractCaptcha.createCode(AbstractCaptcha.java:103)

**Comment by ldaxr** [comment]
@yincangshiwei . Please try "apk add fontconfig ttf-dejavu". We tried this and the NPE is fixed.
